import React from 'react';
import { injectIntl } from 'react-intl';

import { Button, Divider, Grid, Typography } from '@material-ui/core';
import { withStyles, withTheme } from '@material-ui/core/styles';

import {
  FormattedMessage,
  FormPanel,
  PublishedComponent,
  TextInput,
  formatMessage,
  withModulesManager,
} from '@openimis/fe-core';
import PaymentCycleStatusPicker from '../pickers/PaymentCycleStatusPicker';

const styles = (theme) => ({
  tableTitle: theme.table.title,
  item: theme.paper.item,
  fullHeight: {
    height: '100%',
  },
});

const renderHeadPanelTitle = (classes) => (
  <Grid container className={classes.tableTitle}>
    <Grid item>
      <Grid
        container
        align="center"
        justify="center"
        direction="column"
        className={classes.fullHeight}
      >
        <Grid item>
          <Typography>
            <FormattedMessage module="paymentCycle" id="paymentCycle.PaymentCycleHeadPanel.subtitle" />
          </Typography>
        </Grid>
      </Grid>
    </Grid>
  </Grid>
);

class PaymentCycleHeadPanel extends FormPanel {
  render() {
    const {
      edited,
      classes,
      readOnly,
      isCodeValid,
      isCodeValidating,
      codeValidationError,
      codeValidationErrorMessage,
      onFormSave,
      canSaveForm,
      intl,
      modulesManager,
    } = this.props;
    const paymentCycle = { ...edited };
    const showAutoGeneratedCode = modulesManager.getConf('fe-payment_cycle', 'forms.showAutoGeneratedCode', false);
    return (
      <>
        {renderHeadPanelTitle(classes)}
        <Divider />
        <Grid container className={classes.item}>
          {showAutoGeneratedCode && (
          <Grid item xs={3} className={classes.item}>
            <TextInput
              module="paymentCycle"
              label="PaymentCycleHeadPanel.label.code"
              readOnly
              placeholder={paymentCycle?.id ? '' : formatMessage(intl, 'paymentCycle', 'PaymentCycleHeadPanel.label.code.autoGenerated')}
              helperText={formatMessage(intl, 'paymentCycle', 'PaymentCycleHeadPanel.label.code.hint.generatedOnSave')}
              value={paymentCycle?.code}
              inputProps={{ readOnly: true }}
            />
          </Grid>
          )}
          <Grid item xs={3} className={classes.item}>
            <PublishedComponent
              pubRef="core.DatePicker"
              value={paymentCycle?.startDate}
              required
              readOnly={readOnly}
              module="paymentCycle"
              label="PaymentCycleHeadPanel.label.startDate"
              onChange={(v) => this.updateAttribute('startDate', v)}
            />
          </Grid>
          <Grid item xs={3} className={classes.item}>
            <PublishedComponent
              pubRef="core.DatePicker"
              value={paymentCycle?.endDate}
              required
              readOnly={readOnly}
              module="paymentCycle"
              label="PaymentCycleHeadPanel.label.endDate"
              onChange={(v) => this.updateAttribute('endDate', v)}
            />
          </Grid>
          <Grid item xs={3} className={classes.item}>
            <PaymentCycleStatusPicker
              value={paymentCycle?.status}
              required
              withNull={false}
              module="paymentCycle"
              label="PaymentCycleHeadPanel.label.status"
              onChange={(v) => this.updateAttribute('status', v)}
            />
          </Grid>
        </Grid>
        {!readOnly && (
          <Grid container className={classes.item}>
            <Grid item xs={12} className={classes.item}>
              <Button
                color="primary"
                variant="contained"
                onClick={() => onFormSave(edited)}
                disabled={!canSaveForm || !canSaveForm()}
              >
                <FormattedMessage module="paymentCycle" id="PaymentCycleHeadPanel.save" />
              </Button>
            </Grid>
          </Grid>
        )}
      </>
    );
  }
}

export default withModulesManager(
  injectIntl(withTheme(withStyles(styles)(PaymentCycleHeadPanel))),
);
